app:
  title: Portal Plugins Example
  baseUrl: http://localhost:3000

  # Enable all packages by default, this will discover packages from packages/app/package.json
  packages: all

  extensions:
    - nav-item:catalog
    # Configure the catalog index page to be the root page, this is normally mounted on /catalog
    - page:catalog:
        config:
          path: /
    - entity-card:catalog/about
    - entity-card:catalog/labels
    - entity-card:catalog/links:
        config:
          filter:
            kind: component
            metadata.links:
              $exists: true
          # filter: kind:component has:links
          type: info
    # - entity-card:linguist/languages
    - entity-card:catalog-graph/relations:
        config:
          height: 300
    - entity-card:api-docs/has-apis
    - entity-card:api-docs/consumed-apis
    - entity-card:api-docs/provided-apis
    - entity-card:api-docs/providing-components
    - entity-card:api-docs/consuming-components
    # Org Plugin
    - entity-card:org/group-profile
    - entity-card:org/members-list
    - entity-card:org/ownership
    - entity-card:org/user-profile:
        config:
          maxRelations: 5
          hideIcons: true
    # - entity-card:azure-devops/readme

    # Entity page contents
    - entity-content:catalog/overview:
        config:
          group: overview
    - entity-content:api-docs/definition
    - entity-content:api-docs/apis:
        config:
          # example associating with a default group
          group: documentation
    - entity-content:techdocs:
        config:
          group: documentation
    - entity-content:kubernetes/kubernetes:
        config:
          # example disassociating with a default group
          group: false

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Playground]
  locations:
    # Local example data: For Portal Studio, file locations are relative to the root of the project.
    - type: file
      target: ./plugins/catalog-backend-module-playground-kind/playground-example.yaml
    - type: file
      target: ./plugins/team-insights/example-teams.yaml
      rules:
        - allow: [Group, User]

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true
